# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52d2e4a1eeeabb34e4b802d91219a4f649063a26874e900c2d47eaf04261b8b60704da6643bbe19b5b18dd873adecd9690c1dd7687df1dec3389da036f7102fd

test:
  secret_key_base: 277a05a386e506cd761f8b8830cf1234c6cd5f2ad8f7751403849d294912b3b83a511cf74453d6f9986f4e825067665dc82bc3e3de30d80cb5cbb6626fb28ef2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
